### ISSUE TITLE
Strange output with matelightemu

### ISSUE THREAD

**Issue by lucasrangit** [sudoaza/matelife#1]
I'm trying to connect your project with the [Mate-Light emulator](https://github.com/sodoku/matelightemu) and only see a wall of colorful X's. Your app outputs "Transmiting..." as expected. Have you tried the emulator? Is there something else I need to do to run this?

![image](https://user-images.githubusercontent.com/701818/44313441-4723f580-a409-11e8-95f8-58ff06d6f1d2.png)

**Comment by sudoaza** [comment]
I haven't actually, someone mentioned it but hadn't search yet will try it. 
BTW 3 worlds are run in parallel and displayed at the same time for each RGB channel (or its supposed to)

**Comment by lucasrangit** [comment]
> I haven't actually, someone mentioned it but hadn't search yet will try it.

@sudoaza what I'm confused, didn't you make the emulator?

> BTW 3 worlds are run in parallel and displayed at the same time for each RGB channel (or its supposed to)

Hrm, yeah my output is way too colorful. Is there a quick patch to limit the worlds to 1? I don't see how to do it easily.

**Comment by sudoaza** [comment]
> @sudoaza what I'm confused, didn't you make the emulator?

lol no

> Hrm, yeah my output is way too colorful.

about the issue two things were failing, i wasnt updating the screen state after each state (so only the random start was showing up) after fixing if it still was weird and aparently i had mixed the x and y axis. Now works, still need to identify the static states and reset, only doing so when everything dies

> Is there a quick patch to limit the worlds to 1?

Now there is, check MatelifeMono

**Comment by lucasrangit** [comment]
Thanks @sudoaza that fixes it.

I like the mono option.

![image](https://user-images.githubusercontent.com/701818/44550604-0687ed00-a725-11e8-9d99-8bc788eab3c4.png)
